car/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('car_app.urls'))
]

car_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Login(AbstractUser):
    is_employee = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=10)
    emp_id = models.CharField(max_length=10)



class AppointmentSchedule(models.Model):
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()  
    is_active = models.BooleanField(default=True)  



class Appointment(models.Model):
    user = models.ForeignKey(Login, on_delete=models.CASCADE, related_name='appointment')
    schedule = models.ForeignKey(AppointmentSchedule, on_delete=models.CASCADE)
    status = models.IntegerField(default=0)    

car/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CAR CARE</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                {% comment %} <span class="site-heading-upper text-primary mb-3">AUTOMOBLIE COMPANION</span> {% endcomment %}
                <span class="site-heading-lower">CAR CARE</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="#">Home</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="#">About</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="#">Products</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="#">Store</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'assets/img/intro.jpg' %}" alt="..." />
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Login Here</span>
                            <span class="section-heading-lower">Login Here</span>
                        </h2>
                        <p class="mb-3"></p>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'UserAddView' %}">Visit Us Today!</a></div>
                    </div>
                </div>
            </div>
        </section>
        <section class="page-section cta">
            <div class="container">
                <div class="row">
                    <div class="col-xl-9 mx-auto">
                        <div class="cta-inner bg-faded text-center rounded">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper">Our Promise</span>
                                <span class="section-heading-lower">To You</span>
                            </h2>
                            <p class="mb-0">When you walk into our shop to start your day, we are dedicated to providing you with friendly service, a welcoming atmosphere, and above all else, excellent products made with the highest quality ingredients. If you are not satisfied, please let us know and we will do whatever we can to make things right!</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

car/templates/login.html
<!doctype html>
{% load static %}
{% load crispy_forms_filters %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> car care</title>

    <link rel="shortcut icon" href="{% static 'asset1/assets/images/fav.jpg' %}">
    <link rel="stylesheet" href="{% static 'asset1/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'asset1/assets/css/fontawsom-all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'asset1/assets/css/style.css' %}" />
</head>

<body class="h-100">
    <div class="container-fluid full-bg h-100">
        <div class="container h-100">
            <div class="row no-margin h-100">
                <div class="bg-layer d-flex col-md-4">
                    <div class="login-box row">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="login-tab" data-toggle="tab" href="#login" role="tab" aria-controls="home" aria-selected="true"><i class="fas fa-unlock-alt"></i> login</a>
                            </li>
                            {% comment %} <li class="nav-item">
                                <a class="nav-link" id="signup-tab" data-toggle="tab" href="#signup" role="tab" aria-controls="profile" aria-selected="false"><i class="fas fa-user-plus"></i> Register</a>
                            </li>  {% endcomment %}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                create account
                              </button>
                              {% comment %} <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleMod">
                                Register EMPLOYEE
                              </button> {% endcomment %}
                        </ul>
                <form action="#" class="login-form" method="POST">
                    {% csrf_token %}
                        <div class="tab-content w-100" id="myTabContent">
                            <div class="tab-pane   fade show active" id="login" role="tabpanel" aria-labelledby="home-tab">
                               <div class="login-tab">
                                <h3>User login</h3>
                                
                               <div class="form-row">

                                   <input placeholder="Enter Username" name='uname' class="form-control form-control-sm" type="text">
                               </div>

                               <div class="form-row">

                                   <input placeholder="Enter Password" name = 'pass' class="form-control form-control-sm" type="password">
                                  
                               </div>
                            



                                <div class=" forget">

                                   {% comment %} <p> forget password ?</p> {% endcomment %}
                                {% comment %} <button class="btn btn-success btn-sm">Login</button> {% endcomment %}

                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-sm">Get Started</button>
                                </div>
                         </form>
                               </div>
                                </div>

                            </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">REGISTER</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
         {% comment %} form {% endcomment %}
        
            <form id = 'LoginRegister' >
            {% csrf_token %}
         {{form|crispy}}
       
        {% comment %} <div class=" forget">
           <br> {% endcomment %}

          <button type = 'submit' class="btn btn-success w-100 btn-sm" >Sign Up</button>  
          {% comment %} <button type="submit"> submit </button> {% endcomment %}

        </form>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>

{% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
        <!-- Add this script block to your template -->
        



        {% comment %} <script>
          $(document).ready(function() {
            $('#LoginRegister').submit(function(event) {
              // Validate the form before submitting
              if (!validateForm()) {
                event.preventDefault(); // Prevent the form from submitting normally
                return false;
              }
              else {
                $.ajax({
                  type: 'post', // Get the form's method attribute
                  url: 'UserAddView', // Get the form's action attribute
                  data: $(this).serialize(), // Serialize the form data
                  success: function(response) {
                    // Handle the server's response here
                    alert('Form submitted successfully!');
                  },
                  error: function(xhr, status, error) {
                    // Handle errors here
                    alert('An error occurred while submitting the form.');
                    console.error(xhr.responseText);
                  }
                });
              }
            });
        
            function validateForm() {
              // Get the form inputs
              var username = $('#id_username').val().trim();
              var password1 = $('#id_password1').val().trim();
              var password2 = $('#id_password2').val().trim();
              var phone = $('#id_phone_number').val().trim();
        
              // Check for empty fields
              if (username === '' || password1 === '' || password2 === ''  || phone === '') {
                alert('Please fill in all fields.');
                return false;
              }
        
              // Check that passwords match
              if (password1 !== password2) {
                alert('Passwords do not match.');
                return false;
              }
        
              // Check password length
              if (password1.length < 8) {
                alert('Password must be at least 8 characters long.');
                return false;
              }
        
              // Check username length
              if (username.length < 4 || username.length > 20) {
                alert('Username must be between 4 and 20 characters long.');
                return false;
              }
        
              // Check phone number format
              if (!isValidPhoneNumber(phone)) {
                alert('Please enter a valid phone number.');
                return false;
              }
        
              return true;
            }
        
            function isValidPhoneNumber(phone) {
              // Regular expression for phone number validation
              var phoneRegex = /^[0-9]{10}$/;
              return phoneRegex.test(phone);
            }
          });
        </script> {% endcomment %}
        <script src = "{% static 'home/log.js' %}"></script>
          

             



        </div>
         </div>
     </div>
        

                                  

        
        {% comment %} <div class="modal-footer"> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-primary">Save changes</button> {% endcomment %}
        {% comment %} </div> {% endcomment %}
      </div>
    </div>


    <!-- Modal -->
<div class="modal fade" id="exampleMod" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">REGISTER</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
         {% comment %} form {% endcomment %}
         {{employee_form.as_p}}
          
        <div class=" forget">
           <br>

         <button class="btn btn-success w-100 btn-sm">Sign Up</button>
        </div>
         </div>
     </div>

     

                            {% comment %} <div class="tab-pane fade" id="signup" role="tabpanel" aria-labelledby="profile-tab">
                                 <div class="login-tab">
                                 <h3>User login</h3>

                               <div class="form-row">

                                   <input placeholder="Enter Full Name" class="form-control form-control-sm" type="text">
                               </div>

                               <div class="form-row">

                                   <input placeholder="Enter Email Address" class="form-control form-control-sm" type="text">
                               </div>
                                <div class="form-row">

                                   <input placeholder="Enter Password" class="form-control form-control-sm" type="text">
                               </div>
                                <div class="form-row">

                                   <input placeholder="Confirm Password" class="form-control form-control-sm" type="text">
                               </div>
                               <div class=" forget">
                                  <br>

                                <button class="btn btn-success w-100 btn-sm">Sign Up</button>
                               </div>
                                </div>
                            </div>

                        </div> {% endcomment %}




                    </div>
                </div>
            </div>

            
        </div>

    </div>
</body>

{% comment %} <script src="{% static 'asset1/assets/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'asset1/assets/js/popper.min.js' %}"></script>
<script src="{% static 'asset1/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'asset1/assets/js/script.js' %}"></script> {% endcomment %}


</html>